#!/bin/sh
#spectacle -b -n $@ -o /tmp/screenshot.png ; xclip -selection clipboard -target image/png -i /tmp/screenshot.png ; paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
#gnome-screenshot -f /tmp/screenshot.png; xclip -selection clipboard -target image/png -i /tmp/screenshot.png; paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
scrot -z $@ /tmp/screenshot.png; \
xclip -selection clipboard -target image/png -i /tmp/screenshot.png; \
paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
