#!/bin/bash
#spectacle -b -n $@ -o /tmp/screenshot.png ; xclip -selection clipboard -target image/png -i /tmp/screenshot.png ; paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
gnome-screenshot -c $@ -f /tmp/screenshot.png ; xclip -selection clipboard -target image/png -i /tmp/screenshot.png; paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
